### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by chrismessina** [robb/Fantastical-Alfred-Workflow#1]
I've tried downloading the zip and renaming it to 'Fantastical Alfred Workflow.alfredworkflow', but Alfred doesn't want to open it... what am I doing wrong?

**Comment by raygan** [comment]
I'm also pretty lost here; should there be an .alfredworkflow file? How do I install this workflow?

**Comment by smithjw** [comment]
Hey @chrismessina & @raygan,

I've forked this [here](https://github.com/smithjw/Fantastical-Alfred-Workflow) which adds a .alfredworkflow file for easy installation and also adds the item to your Calendar immediately.

cc @robb

**Comment by bvp663** [comment]
I was really confused on how to install as well. Thanks @smithjw!

**Comment by robb** [comment]
I've added a [download to the Releases page](https://github.com/robb/Fantastical-Alfred-Workflow/releases/latest), that's probably the best way to install :sparkles: . Sorry for the delay!
